<?php
/**
 * Created by PhpStorm.
 * User: HOANDHTB
 * Date: 8/2/2016
 * Time: 12:19 AM
 */
namespace app\modules\admin\components;
use yii\web\Controller;

class BaseController extends Controller
{
    /*public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }*/
}